### ISSUE TITLE
想问一下最后是怎么查到本地不支持cookie的

### ISSUE THREAD

**Issue by Li-YiLin** [anthonyliu0417/BIPT-Pass-Gen#1]

**Comment by Li-YiLin** [comment]
我觉得你是直接点开HTML文件测试的，而不是启动一个服务从服务里访问HTML，只有当服务启动的时候浏览器才会进行通信进而产生cookie。
从写代码的角度出发我觉得能发现是cookie的问题是难的，想问问你的debug思路

**Comment by anthonyliu0417** [comment]
确实是直接点开文件测试的，没搞那个本地调试环境，就直接用文本硬写然后点开测试的，也不太清楚会有这种影响。最后就发现扔在服务器上运行就没问题了。哈哈哈 学到了，谢谢
